- hosts: elastic.ru-central1.internal
  become: yes
  gather_facts: true
  tasks:

  - name: Установка elasticsearch
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.5.0-amd64.deb"

  - name: Копируем конфиг файл elasticsearch
    copy:
      src: /home/user/ansible/elastic.yml
      dest: /etc/elasticsearch/elasticsearch.yml

  - name: Перезапускаем службы
    systemd:
      state: started
      name: elasticsearch