---
- name: Установка Zabbix Agent на группу серверов web
  hosts: web
  become: true
  tasks:
    - name: Установка необходимых пакетов
      apt:
        name:
          - zabbix-agent
        state: present

    - name: Создание директории для логов Zabbix Agent
      command: mkdir -p /var/log/zabbix/
      become_user: root

    - name: Установка прав на директорию логов Zabbix Agent
      command: chown zabbix /var/log/zabbix/
      become_user: root

    - name: Копирование конфигурационного файла Zabbix Agent
      template:
        src: /home/user/ansible/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify: restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
